// Generated by `flutterfire configure` against the real "roost-dcc00"
// Firebase project — see docs/ios-dev-setup.md for the setup this came from.
//
// Firebase Cloud Messaging backs FR5.2 (message notifications) on both
// platforms, and FR5.1 (call wake) on Android only — iOS's call-wake path
// goes through flutter_callkit_incoming's own PushKit registration instead,
// no Firebase involved there (see lib/services/push_service.dart).
//
// `flutterfire configure` also generates android/app/google-services.json,
// ios/Runner/GoogleService-Info.plist, firebase.json, and applies the
// Google Services Gradle plugin — none of that is used here (this file is
// the only thing Firebase.initializeApp() reads) and the Gradle plugin is
// actively harmful on Android (see docs/ios-dev-setup.md). Re-running
// `flutterfire configure` regenerates all of that again; revert everything
// except this file afterward.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('DefaultFirebaseOptions have not been configured for web.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions.currentPlatform is only used on Android and iOS in this app.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3QNwgcKLuB3sXSRX0ntr5WcU7VXhfmP0',
    appId: '1:828396399344:android:4d492c4b69830cb385b035',
    messagingSenderId: '828396399344',
    projectId: 'roost-dcc00',
    storageBucket: 'roost-dcc00.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaoP2OMdUMBc_E-6pFz203AdMf--8SXP8',
    appId: '1:828396399344:ios:f6861f29c0aad76d85b035',
    messagingSenderId: '828396399344',
    projectId: 'roost-dcc00',
    storageBucket: 'roost-dcc00.firebasestorage.app',
    iosBundleId: 'me.holzeis.roost.roost',
  );
}
